--- #EC2 module provisioning example
- hosts: localhost
  connection: local
  remote_user: test
  become: yes
  gather_facts: no
  vars_files: 
  - files/awscreds.yml
  tasks:
  - name: More advanced  provisioning of two t2.micro EC2 Instances
    ec2:
      aws_access_key: "{{ aws_id }}"
      aws_secret_key: "{{ aws_key }}"
      region: "{{ aws_region }}"
      image: ami-a4c7edb2
      instance_type: t2.micro
      count: 2 
      vpc_subnet_id: subnet-87de8dce
      assign_public_ip: yes
