--- # EC2 Key module
- hosts: localhost
  connection: local
  remote_user: test
  become: yes
  gather_facts: yes
  vars_files:
  - files/awscreds.yml
  tasks:
  - name: Create a new key pair - MyKeyPairTestAWS
    ec2_key:
      aws_access_key: "{{ aws_id }}"
      aws_secret_key: "{{ aws_key }}"
      name: MyKeyPairTestAWS
      region: us-west-2
      state: present
